# Generated by Django 3.2.6 on 2021-09-12 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_purchase', models.CharField(default=uuid.uuid4, editable=False, max_length=7, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ManyToManyField(related_name='purchased', to='roda_purchase.Product')),
            ],
        ),
    ]
