# Generated by Django 3.2.6 on 2021-09-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roda_purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='cod_purchase',
            new_name='sku',
        ),
    ]
