# Generated by Django 3.2.6 on 2021-09-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roda_purchase', '0003_auto_20210912_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku_purchase',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(related_name='purchased', to='roda_purchase.Product'),
        ),
    ]
