# Generated by Django 3.2.6 on 2021-09-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roda_purchase', '0006_alter_purchase_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
